# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Islectl < Formula
  desc ""
  homepage "https://github.com/islandora-devops/islectl"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.1/islectl_Darwin_x86_64.tar.gz"
      sha256 "7634d5306b4ffbf0162522ec1e451fc761362a606c7ba86d9590a32e28261a3c"

      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.1/islectl_Darwin_arm64.tar.gz"
      sha256 "f9197048f04b36c897a7ee3424ee6d1486e04879a56b49f4f04e6b2fd199275d"

      def install
        bin.install "islectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.1/islectl_Linux_x86_64.tar.gz"
        sha256 "e5fe4a287a2329e2fbb3a3abf61468bd81ad4f25d245d6f9859bec1fbd02a409"

        def install
          bin.install "islectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.1/islectl_Linux_arm64.tar.gz"
        sha256 "83b9f11cbcc45ea82426caa7f205ed9d47a5030a150acffce387de81201831da"

        def install
          bin.install "islectl"
        end
      end
    end
  end
end
