# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Islectl < Formula
  desc ""
  homepage "https://github.com/islandora-devops/islectl"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.5.1/islectl_Darwin_x86_64.tar.gz"
      sha256 "af0aea1ae951f89aae5770575adc0c5288cb8dbb2eb1f7eaf251619ea290da1a"

      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.5.1/islectl_Darwin_arm64.tar.gz"
      sha256 "341c1fc87853cc2c118170c503a9d8d9b6c2130405426366af1b2b0020076d09"

      def install
        bin.install "islectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Islandora-Devops/islectl/releases/download/0.5.1/islectl_Linux_x86_64.tar.gz"
        sha256 "58f2c2e66a32c993ea17fea25f89fe32c3da806ad32dcfa8170036a6fc26c0e2"

        def install
          bin.install "islectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Islandora-Devops/islectl/releases/download/0.5.1/islectl_Linux_arm64.tar.gz"
        sha256 "675e4309cd9cb9e93c8f4cfe217bc7126c9f7c522e894329e8cd50807b23897f"

        def install
          bin.install "islectl"
        end
      end
    end
  end
end
