# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Islectl < Formula
  desc ""
  homepage "https://github.com/islandora-devops/islectl"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.3/islectl_Darwin_x86_64.tar.gz"
      sha256 "a8a56f0d359b4a8a5d594f84c1b4ec4220b85761433678981fa52c4b190079d8"

      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.3/islectl_Darwin_arm64.tar.gz"
      sha256 "2707cbccd3f5197a7bd93b3fe3ed73d0899167117378ce85e2a908415671cbae"

      def install
        bin.install "islectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.3/islectl_Linux_x86_64.tar.gz"
        sha256 "1221abee9f3e9d8520d260624a3f68206a89d20f4c90776d3d493b81f06902aa"

        def install
          bin.install "islectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.3/islectl_Linux_arm64.tar.gz"
        sha256 "ec49bcf42361812c15fd0728fe82c80481ade49ca731cf67ddca24b159f740c0"

        def install
          bin.install "islectl"
        end
      end
    end
  end
end
